routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Auth::routes(['register' => false]);

Route::get('/', 'IndexController@index');

Auth::routes();

Route::middleware('auth')->prefix('admin')->name('admin.')->namespace('Admin')->group(function(){

  Route::get('/', 'HomeController@index')->name('home.index');

  Route::resource('pages', 'PageController');

  Route::resource('sections', 'SectionController', ['except' => ['index']]);

});

Route::middleware('auth')->prefix('admin')->name('admin.')->namespace('Admin')->group(function(){

  Route::get('sections/{section}', 'SectionController@index')->name('sections.index');

  Route::get('sections/element/{section}', 'SectionController@element')->name('sections.element');

});

resources/views/admin/home.blade.php
@extends('layouts.admin_app')

@section('sidebar')
  @include('layouts.sidebar.admin_app')
@endsection

@section('content')

            <div class="container-fluid">

              <!-- Page Heading -->
              <div class="d-sm-flex align-items-center justify-content-between mb-4">
                <h1 class="h3 mb-0 text-gray-800">Dashboard</h1>
                <a href="{{ route('admin.pages.index') }}" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fas fa-download fa-sm text-white-50"></i>Tutte le pagine</a>
              </div>
            </div>
            <!-- /.container-fluid -->
          @endsection