routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Auth::routes(['register' => false]);

Route::get('/', 'IndexController@index');

Auth::routes();

Route::middleware('auth')->prefix('admin')->name('admin.')->namespace('Admin')->group(function(){

  Route::get('/', 'HomeController@index')->name('home.index');

  Route::resource('pages', 'PageController');

  Route::resource('sections', 'SectionController', ['except' => ['index']]);

});

Route::middleware('auth')->prefix('admin')->name('admin.')->namespace('Admin')->group(function(){

  Route::get('sections/{section}', 'SectionController@index')->name('sections.index');

  Route::get('sections/element/{section}', 'SectionController@element')->name('sections.element');

});

resources/views/admin/pages/create.blade.php
@extends('layouts.admin_app')

@section('sidebar')
  @include('layouts.sidebar.admin_app')
@endsection

@section('content')

  <div class="container">
    <div class="row">
      <div class="col-12">
        <h1>Aggiungi Nuova Pagina</h1>
        <form class="form-group" action="{{ route('admin.pages.store') }}" method="POST" enctype="multipart/form-data">
          @csrf
          <input type="hidden" name="user_id" value={{Auth::user()->id}} >

          {{-- *** PAGE *** --}}

          <div class="form-group">
            <label for="title">Titolo</label>
            <input type="text" name="title" class="form-control">
          </div>
          <div class="form-group" >
            <label for="description">Descrizione</label>
            <textarea name="description" class="form-control" rows="8" cols="80"></textarea>
          </div>

          <div class="form-group">
            <input type="submit" value="Crea Pagina" class="form-control">
          </div>

        </form>
      </div>
    </div>
  </div>

@endsection

resources/views/admin/pages/index.blade.php
@extends('layouts.admin_app')

@section('sidebar')
  @include('layouts.sidebar.admin_app')
@endsection

@section('content')
  <div class="container-fluid">

    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
      <h1 class="h3 mb-0 text-gray-800">Pages</h1>
    </div>

    <!-- Content Row -->

    <div class="row">

      <!-- Area Chart -->
      <div class="col-xl-12 col-lg-12">
        <div class="card shadow mb-4">
          <!-- Card Header - Dropdown -->
          <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
            <h6 class="m-0 font-weight-bold text-primary">Earnings Overview</h6>
            <div class="dropdown no-arrow">
              <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
              </a>
              <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                <div class="dropdown-header">Dropdown Header:</div>
                <a class="dropdown-item" href="{{ route('admin.pages.create') }}">Add Pages</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Something else here</a>
              </div>
            </div>
          </div>
          <!-- Card Body -->
          <div class="card-body">
            <table class="table">
              <thead>
                <tr>
                  <th scope="col">ID</th>
                  <th scope="col">Title</th>
                  <th scope="col">Description</th>
                  <th scope="col">Date</th>
                  <th scope="col"></th>
                  <th scope="col"></th>
                  <th scope="col"></th>
                </tr>
              </thead>
              <tbody>
                @php
                $number = 0
                @endphp
                @foreach ($pages as $page)
                  <tr>
                    <td>{{ $number += 1 }}</td>
                    <td>{{ $page->title }}</td>
                    <td>{{ str_limit($page->description, 50, '...') }}</td>
                    <td>{{ $page->created_at->format('d/m/Y') }}</td>
                    <td>
                      <a href="{{ route('admin.pages.show', $page->id) }}" class="btn btn-primary">View</a>
                    </td>
                    <td>
                      <a href="{{ route('admin.sections.index', $page->id) }}" class="btn btn-secondary">Edit</a>
                    </td>
                    <td>
                      <form action="{{ route('admin.pages.destroy', $page->id) }}" method="post">
                        @csrf
                        @method('DELETE')
                        <input class="btn btn-danger" type="submit" value="Elimina">
                      </form>
                    </td>
                  </tr>
                @endforeach
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- /.container-fluid -->
@endsection

resources/views/admin/pages/show.blade.php
@extends('layouts.admin_app')

@section('sidebar')
  @include('layouts.sidebar.show')
@endsection

@section('content')

<div id="template-base">

  <div class="container">
      @foreach ($elements as $element)
        <div class="title">
          @foreach ($element[0] as $item)
            <div class="row">
              <div class="col-12 title__item">
                <h1>{{ $item->text }}</h1>
              </div>
            </div>
          @endforeach
        </div>
        <div class="subtitle">
          @foreach ($element[1] as $item)
            <div class="row">
              <div class="col-12 subtitle__item">
                <h4>{{ $item->text }}</h4>
              </div>
            </div>
          @endforeach
        </div>
        <div class="image">
          @foreach ($element[2] as $item)
            <div class="row">
              <div class="col-12">
                <div class="image__item" style="background-image: url('{{ $item->path }}');">
                </div>
              </div>
            </div>
          @endforeach
        </div>
        <div class="description">
          @foreach ($element[3] as $item)
            <div class="row">
              <div class="col-12 description__item">
                <p>{{ $item->text }}</p>
              </div>
            </div>
          @endforeach
        </div>
      @endforeach
  </div>

</div>

@endsection